webdriver {
  driver = chrome
}

serenity {
  project.name = "QA Automation Challenge - Juan Chacon"
  take.screenshots = FOR_FAILURES
}

webdriver.timeouts {
  implicitlywait = 0
  fluentwait = 10000
}

chrome {
  switches = "--start-maximized"
}